python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 0 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 1 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 2 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 3 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 4 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 5 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 6 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 7 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 8 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 9 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 10 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 11 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 12 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 13 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 14 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 15 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 16 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 17 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 18 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 19 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 20 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 21 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 22 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 23 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 24 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 25 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 26 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 27 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 28 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
python3 core/run/run_utility.py --task weight_utils --learner sgd_with_hesscale --seed 29 --lr 0.01 --network small_fully_connected_relu --n_samples 2000
