python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network fully_connected_sigmoid --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network small_fully_connected_sigmoid --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network fully_connected_sigmoid_gates --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network small_fully_connected_sigmoid_gates --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network fully_connected_leakyrelu --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network small_fully_connected_leakyrelu --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network fully_connected_leakyrelu_gates --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network small_fully_connected_leakyrelu_gates --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network fully_connected_tanh --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network small_fully_connected_tanh --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network fully_connected_tanh_gates --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network small_fully_connected_tanh_gates --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network small_fully_connected_crelu_gates --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network fully_connected_crelu --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network small_fully_connected_crelu --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network fully_connected_crelu_gates --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network convolutional_network_crelu --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network small_fully_connected_relu_gates --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network fully_connected_relu --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network small_fully_connected_relu --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network fully_connected_relu_gates --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network convolutional_network_relu --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network convolutional_network_relu_with_hooks --n_samples 1000000
python3 core/run/run.py --task input_permuted_mnist --learner sgd --seed 0 --lr 0.001 --weight_decay 0.01 --network fully_connected_relu_with_hooks --n_samples 1000000